export interface Color {
  colorName: string;
  bgClass: string;
  textClass: string;
  softClass: string;
  iconClass: string;
}

export const COLORS: Color[][] = [
  // RED
  [
    {
      colorName: 'color-red-50',
      bgClass: 'bg-red-50',
      iconClass: 'after:bg-red-500!',
      textClass: 'text-red-500',
      softClass: 'text-red-50',
    },
    {
      colorName: 'color-red-100',
      bgClass: 'bg-red-100',
      iconClass: 'after:bg-red-500!',
      textClass: 'text-red-500',
      softClass: 'text-red-100',
    },
    {
      colorName: 'color-red-200',
      bgClass: 'bg-red-200',
      iconClass: 'after:bg-red-500!',
      textClass: 'text-red-500',
      softClass: 'text-red-200',
    },
    {
      colorName: 'color-red-300',
      bgClass: 'bg-red-300',
      iconClass: 'after:bg-red-700!',
      textClass: 'text-red-700',
      softClass: 'text-red-300',
    },
    {
      colorName: 'color-red-400',
      bgClass: 'bg-red-400',
      iconClass: 'after:bg-red-800!',
      textClass: 'text-red-800',
      softClass: 'text-red-400',
    },
    {
      colorName: 'color-red-500',
      bgClass: 'bg-red-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-red-500',
    },
    {
      colorName: 'color-red-600',
      bgClass: 'bg-red-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-red-600',
    },
    {
      colorName: 'color-red-700',
      bgClass: 'bg-red-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-red-700',
    },
    {
      colorName: 'color-red-800',
      bgClass: 'bg-red-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-red-800',
    },
    {
      colorName: 'color-red-900',
      bgClass: 'bg-red-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-red-900',
    },
    {
      colorName: 'color-red-950',
      bgClass: 'bg-red-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-red-950',
    },
  ],
  // ORANGE
  [
    {
      colorName: 'color-orange-50',
      bgClass: 'bg-orange-50',
      iconClass: 'after:bg-orange-500!',
      textClass: 'text-orange-500',
      softClass: 'text-orange-50',
    },
    {
      colorName: 'color-orange-100',
      bgClass: 'bg-orange-100',
      iconClass: 'after:bg-orange-500!',
      textClass: 'text-orange-500',
      softClass: 'text-orange-100',
    },
    {
      colorName: 'color-orange-200',
      bgClass: 'bg-orange-200',
      iconClass: 'after:bg-orange-500!',
      textClass: 'text-orange-500',
      softClass: 'text-orange-200',
    },
    {
      colorName: 'color-orange-300',
      bgClass: 'bg-orange-300',
      iconClass: 'after:bg-orange-700!',
      textClass: 'text-orange-700',
      softClass: 'text-orange-300',
    },
    {
      colorName: 'color-orange-400',
      bgClass: 'bg-orange-400',
      iconClass: 'after:bg-orange-800!',
      textClass: 'text-orange-800',
      softClass: 'text-orange-400',
    },
    {
      colorName: 'color-orange-500',
      bgClass: 'bg-orange-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-orange-500',
    },
    {
      colorName: 'color-orange-600',
      bgClass: 'bg-orange-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-orange-600',
    },
    {
      colorName: 'color-orange-700',
      bgClass: 'bg-orange-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-orange-700',
    },
    {
      colorName: 'color-orange-800',
      bgClass: 'bg-orange-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-orange-800',
    },
    {
      colorName: 'color-orange-900',
      bgClass: 'bg-orange-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-orange-900',
    },
    {
      colorName: 'color-orange-950',
      bgClass: 'bg-orange-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-orange-950',
    },
  ],
  // AMBER
  [
    {
      colorName: 'color-amber-50',
      bgClass: 'bg-amber-50',
      iconClass: 'after:bg-amber-500!',
      textClass: 'text-amber-500',
      softClass: 'text-amber-50',
    },
    {
      colorName: 'color-amber-100',
      bgClass: 'bg-amber-100',
      iconClass: 'after:bg-amber-500!',
      textClass: 'text-amber-500',
      softClass: 'text-amber-100',
    },
    {
      colorName: 'color-amber-200',
      bgClass: 'bg-amber-200',
      iconClass: 'after:bg-amber-500!',
      textClass: 'text-amber-500',
      softClass: 'text-amber-200',
    },
    {
      colorName: 'color-amber-300',
      bgClass: 'bg-amber-300',
      iconClass: 'after:bg-amber-500!',
      textClass: 'text-amber-700',
      softClass: 'text-amber-300',
    },
    {
      colorName: 'color-amber-400',
      bgClass: 'bg-amber-400',
      iconClass: 'after:bg-amber-800!',
      textClass: 'text-amber-800',
      softClass: 'text-amber-400',
    },
    {
      colorName: 'color-amber-500',
      bgClass: 'bg-amber-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-amber-500',
    },
    {
      colorName: 'color-amber-600',
      bgClass: 'bg-amber-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-amber-600',
    },
    {
      colorName: 'color-amber-700',
      bgClass: 'bg-amber-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-amber-700',
    },
    {
      colorName: 'color-amber-800',
      bgClass: 'bg-amber-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-amber-800',
    },
    {
      colorName: 'color-amber-900',
      bgClass: 'bg-amber-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-amber-900',
    },
    {
      colorName: 'color-amber-950',
      bgClass: 'bg-amber-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-amber-950',
    },
  ],
  // YELLOW
  [
    {
      colorName: 'color-yellow-50',
      bgClass: 'bg-yellow-50',
      iconClass: 'after:bg-yellow-500!',
      textClass: 'text-yellow-500',
      softClass: 'text-yellow-50',
    },
    {
      colorName: 'color-yellow-100',
      bgClass: 'bg-yellow-100',
      iconClass: 'after:bg-yellow-500!',
      textClass: 'text-yellow-500',
      softClass: 'text-yellow-100',
    },
    {
      colorName: 'color-yellow-200',
      bgClass: 'bg-yellow-200',
      iconClass: 'after:bg-yellow-500!',
      textClass: 'text-yellow-500',
      softClass: 'text-yellow-200',
    },
    {
      colorName: 'color-yellow-300',
      bgClass: 'bg-yellow-300',
      iconClass: 'after:bg-yellow-700!',
      textClass: 'text-yellow-700',
      softClass: 'text-yellow-300',
    },
    {
      colorName: 'color-yellow-400',
      bgClass: 'bg-yellow-400',
      iconClass: 'after:bg-yellow-800!',
      textClass: 'text-yellow-800',
      softClass: 'text-yellow-400',
    },
    {
      colorName: 'color-yellow-500',
      bgClass: 'bg-yellow-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-yellow-500',
    },
    {
      colorName: 'color-yellow-600',
      bgClass: 'bg-yellow-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-yellow-600',
    },
    {
      colorName: 'color-yellow-700',
      bgClass: 'bg-yellow-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-yellow-700',
    },
    {
      colorName: 'color-yellow-800',
      bgClass: 'bg-yellow-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-yellow-800',
    },
    {
      colorName: 'color-yellow-900',
      bgClass: 'bg-yellow-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-yellow-900',
    },
    {
      colorName: 'color-yellow-950',
      bgClass: 'bg-yellow-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-yellow-950',
    },
  ],
  // LIME
  [
    {
      colorName: 'color-lime-50',
      bgClass: 'bg-lime-50',
      iconClass: 'after:bg-lime-500!',
      textClass: 'text-lime-500',
      softClass: 'text-lime-50',
    },
    {
      colorName: 'color-lime-100',
      bgClass: 'bg-lime-100',
      iconClass: 'after:bg-lime-500!',
      textClass: 'text-lime-500',
      softClass: 'text-lime-100',
    },
    {
      colorName: 'color-lime-200',
      bgClass: 'bg-lime-200',
      iconClass: 'after:bg-lime-500!',
      textClass: 'text-lime-500',
      softClass: 'text-lime-200',
    },
    {
      colorName: 'color-lime-300',
      bgClass: 'bg-lime-300',
      iconClass: 'after:bg-lime-700!',
      textClass: 'text-lime-700',
      softClass: 'text-lime-300',
    },
    {
      colorName: 'color-lime-400',
      bgClass: 'bg-lime-400',
      iconClass: 'after:bg-lime-800!',
      textClass: 'text-lime-800',
      softClass: 'text-lime-400',
    },
    {
      colorName: 'color-lime-500',
      bgClass: 'bg-lime-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-lime-500',
    },
    {
      colorName: 'color-lime-600',
      bgClass: 'bg-lime-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-lime-600',
    },
    {
      colorName: 'color-lime-700',
      bgClass: 'bg-lime-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-lime-700',
    },
    {
      colorName: 'color-lime-800',
      bgClass: 'bg-lime-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-lime-800',
    },
    {
      colorName: 'color-lime-900',
      bgClass: 'bg-lime-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-lime-900',
    },
    {
      colorName: 'color-lime-950',
      bgClass: 'bg-lime-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-lime-950',
    },
  ],
  // GREEN
  [
    {
      colorName: 'color-green-50',
      bgClass: 'bg-green-50',
      iconClass: 'after:bg-green-500!',
      textClass: 'text-green-500',
      softClass: 'text-green-50',
    },
    {
      colorName: 'color-green-100',
      bgClass: 'bg-green-100',
      iconClass: 'after:bg-green-500!',
      textClass: 'text-green-500',
      softClass: 'text-green-100',
    },
    {
      colorName: 'color-green-200',
      bgClass: 'bg-green-200',
      iconClass: 'after:bg-green-500!',
      textClass: 'text-green-500',
      softClass: 'text-green-200',
    },
    {
      colorName: 'color-green-300',
      bgClass: 'bg-green-300',
      iconClass: 'after:bg-green-700!',
      textClass: 'text-green-700',
      softClass: 'text-green-300',
    },
    {
      colorName: 'color-green-400',
      bgClass: 'bg-green-400',
      iconClass: 'after:bg-green-800!',
      textClass: 'text-green-800',
      softClass: 'text-green-400',
    },
    {
      colorName: 'color-green-500',
      bgClass: 'bg-green-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-green-500',
    },
    {
      colorName: 'color-green-600',
      bgClass: 'bg-green-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-green-600',
    },
    {
      colorName: 'color-green-700',
      bgClass: 'bg-green-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-green-700',
    },
    {
      colorName: 'color-green-800',
      bgClass: 'bg-green-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-green-800',
    },
    {
      colorName: 'color-green-900',
      bgClass: 'bg-green-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-green-900',
    },
    {
      colorName: 'color-green-950',
      bgClass: 'bg-green-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-green-950',
    },
  ],
  // EMERALD
  [
    {
      colorName: 'color-emerald-50',
      bgClass: 'bg-emerald-50',
      iconClass: 'after:bg-emerald-500!',
      textClass: 'text-emerald-500',
      softClass: 'text-emerald-50',
    },
    {
      colorName: 'color-emerald-100',
      bgClass: 'bg-emerald-100',
      iconClass: 'after:bg-emerald-500!',
      textClass: 'text-emerald-500',
      softClass: 'text-emerald-100',
    },
    {
      colorName: 'color-emerald-200',
      bgClass: 'bg-emerald-200',
      iconClass: 'after:bg-emerald-500!',
      textClass: 'text-emerald-500',
      softClass: 'text-emerald-200',
    },
    {
      colorName: 'color-emerald-300',
      bgClass: 'bg-emerald-300',
      iconClass: 'after:bg-emerald-700!',
      textClass: 'text-emerald-700',
      softClass: 'text-emerald-300',
    },
    {
      colorName: 'color-emerald-400',
      bgClass: 'bg-emerald-400',
      iconClass: 'after:bg-emerald-800!',
      textClass: 'text-emerald-800',
      softClass: 'text-emerald-400',
    },
    {
      colorName: 'color-emerald-500',
      bgClass: 'bg-emerald-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-emerald-500',
    },
    {
      colorName: 'color-emerald-600',
      bgClass: 'bg-emerald-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-emerald-600',
    },
    {
      colorName: 'color-emerald-700',
      bgClass: 'bg-emerald-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-emerald-700',
    },
    {
      colorName: 'color-emerald-800',
      bgClass: 'bg-emerald-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-emerald-800',
    },
    {
      colorName: 'color-emerald-900',
      bgClass: 'bg-emerald-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-emerald-900',
    },
    {
      colorName: 'color-emerald-950',
      bgClass: 'bg-emerald-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-emerald-950',
    },
  ],
  // TEAL
  [
    {
      colorName: 'color-teal-50',
      bgClass: 'bg-teal-50',
      iconClass: 'after:bg-teal-500!',
      textClass: 'text-teal-500',
      softClass: 'text-teal-50',
    },
    {
      colorName: 'color-teal-100',
      bgClass: 'bg-teal-100',
      iconClass: 'after:bg-teal-500!',
      textClass: 'text-teal-500',
      softClass: 'text-teal-100',
    },
    {
      colorName: 'color-teal-200',
      bgClass: 'bg-teal-200',
      iconClass: 'after:bg-teal-500!',
      textClass: 'text-teal-500',
      softClass: 'text-teal-200',
    },
    {
      colorName: 'color-teal-300',
      bgClass: 'bg-teal-300',
      iconClass: 'after:bg-teal-700!',
      textClass: 'text-teal-700',
      softClass: 'text-teal-300',
    },
    {
      colorName: 'color-teal-400',
      bgClass: 'bg-teal-400',
      iconClass: 'after:bg-teal-800!',
      textClass: 'text-teal-800',
      softClass: 'text-teal-400',
    },
    {
      colorName: 'color-teal-500',
      bgClass: 'bg-teal-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-teal-500',
    },
    {
      colorName: 'color-teal-600',
      bgClass: 'bg-teal-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-teal-600',
    },
    {
      colorName: 'color-teal-700',
      bgClass: 'bg-teal-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-teal-700',
    },
    {
      colorName: 'color-teal-800',
      bgClass: 'bg-teal-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-teal-800',
    },
    {
      colorName: 'color-teal-900',
      bgClass: 'bg-teal-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-teal-900',
    },
    {
      colorName: 'color-teal-950',
      bgClass: 'bg-teal-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-teal-950',
    },
  ],
  // CYAN
  [
    {
      colorName: 'color-cyan-50',
      bgClass: 'bg-cyan-50',
      iconClass: 'after:bg-cyan-500!',
      textClass: 'text-cyan-500',
      softClass: 'text-cyan-50',
    },
    {
      colorName: 'color-cyan-100',
      bgClass: 'bg-cyan-100',
      iconClass: 'after:bg-cyan-500!',
      textClass: 'text-cyan-500',
      softClass: 'text-cyan-100',
    },
    {
      colorName: 'color-cyan-200',
      bgClass: 'bg-cyan-200',
      iconClass: 'after:bg-cyan-500!',
      textClass: 'text-cyan-500',
      softClass: 'text-cyan-200',
    },
    {
      colorName: 'color-cyan-300',
      bgClass: 'bg-cyan-300',
      iconClass: 'after:bg-cyan-700!',
      textClass: 'text-cyan-700',
      softClass: 'text-cyan-300',
    },
    {
      colorName: 'color-cyan-400',
      bgClass: 'bg-cyan-400',
      iconClass: 'after:bg-cyan-800!',
      textClass: 'text-cyan-800',
      softClass: 'text-cyan-400',
    },
    {
      colorName: 'color-cyan-500',
      bgClass: 'bg-cyan-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-cyan-500',
    },
    {
      colorName: 'color-cyan-600',
      bgClass: 'bg-cyan-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-cyan-600',
    },
    {
      colorName: 'color-cyan-700',
      bgClass: 'bg-cyan-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-cyan-700',
    },
    {
      colorName: 'color-cyan-800',
      bgClass: 'bg-cyan-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-cyan-800',
    },
    {
      colorName: 'color-cyan-900',
      bgClass: 'bg-cyan-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-cyan-900',
    },
    {
      colorName: 'color-cyan-950',
      bgClass: 'bg-cyan-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-cyan-950',
    },
  ],
  // SKY
  [
    {
      colorName: 'color-sky-50',
      bgClass: 'bg-sky-50',
      iconClass: 'after:bg-sky-500!',
      textClass: 'text-sky-500',
      softClass: 'text-sky-50',
    },
    {
      colorName: 'color-sky-100',
      bgClass: 'bg-sky-100',
      iconClass: 'after:bg-sky-500!',
      textClass: 'text-sky-500',
      softClass: 'text-sky-100',
    },
    {
      colorName: 'color-sky-200',
      bgClass: 'bg-sky-200',
      iconClass: 'after:bg-sky-500!',
      textClass: 'text-sky-500',
      softClass: 'text-sky-200',
    },
    {
      colorName: 'color-sky-300',
      bgClass: 'bg-sky-300',
      iconClass: 'after:bg-sky-700!',
      textClass: 'text-sky-700',
      softClass: 'text-sky-300',
    },
    {
      colorName: 'color-sky-400',
      bgClass: 'bg-sky-400',
      iconClass: 'after:bg-sky-800!',
      textClass: 'text-sky-800',
      softClass: 'text-sky-400',
    },
    {
      colorName: 'color-sky-500',
      bgClass: 'bg-sky-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-sky-500',
    },
    {
      colorName: 'color-sky-600',
      bgClass: 'bg-sky-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-sky-600',
    },
    {
      colorName: 'color-sky-700',
      bgClass: 'bg-sky-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-sky-700',
    },
    {
      colorName: 'color-sky-800',
      bgClass: 'bg-sky-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-sky-800',
    },
    {
      colorName: 'color-sky-900',
      bgClass: 'bg-sky-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-sky-900',
    },
    {
      colorName: 'color-sky-950',
      bgClass: 'bg-sky-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-sky-950',
    },
  ],
  // BLUE
  [
    {
      colorName: 'color-blue-50',
      bgClass: 'bg-blue-50',
      iconClass: 'after:bg-blue-500!',
      textClass: 'text-blue-500',
      softClass: 'text-blue-50',
    },
    {
      colorName: 'color-blue-100',
      bgClass: 'bg-blue-100',
      iconClass: 'after:bg-blue-500!',
      textClass: 'text-blue-500',
      softClass: 'text-blue-100',
    },
    {
      colorName: 'color-blue-200',
      bgClass: 'bg-blue-200',
      iconClass: 'after:bg-blue-500!',
      textClass: 'text-blue-500',
      softClass: 'text-blue-200',
    },
    {
      colorName: 'color-blue-300',
      bgClass: 'bg-blue-300',
      iconClass: 'after:bg-blue-700!',
      textClass: 'text-blue-700',
      softClass: 'text-blue-300',
    },
    {
      colorName: 'color-blue-400',
      bgClass: 'bg-blue-400',
      iconClass: 'after:bg-blue-800!',
      textClass: 'text-blue-800',
      softClass: 'text-blue-400',
    },
    {
      colorName: 'color-blue-500',
      bgClass: 'bg-blue-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-blue-500',
    },
    {
      colorName: 'color-blue-600',
      bgClass: 'bg-blue-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-blue-600',
    },
    {
      colorName: 'color-blue-700',
      bgClass: 'bg-blue-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-blue-700',
    },
    {
      colorName: 'color-blue-800',
      bgClass: 'bg-blue-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-blue-800',
    },
    {
      colorName: 'color-blue-900',
      bgClass: 'bg-blue-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-blue-900',
    },
    {
      colorName: 'color-blue-950',
      bgClass: 'bg-blue-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-blue-950',
    },
  ],
  // INDIGO
  [
    {
      colorName: 'color-indigo-50',
      bgClass: 'bg-indigo-50',
      iconClass: 'after:bg-indigo-500!',
      textClass: 'text-indigo-500',
      softClass: 'text-indigo-50',
    },
    {
      colorName: 'color-indigo-100',
      bgClass: 'bg-indigo-100',
      iconClass: 'after:bg-indigo-500!',
      textClass: 'text-indigo-500',
      softClass: 'text-indigo-100',
    },
    {
      colorName: 'color-indigo-200',
      bgClass: 'bg-indigo-200',
      iconClass: 'after:bg-indigo-500!',
      textClass: 'text-indigo-500',
      softClass: 'text-indigo-200',
    },
    {
      colorName: 'color-indigo-300',
      bgClass: 'bg-indigo-300',
      iconClass: 'after:bg-indigo-700!',
      textClass: 'text-indigo-700',
      softClass: 'text-indigo-300',
    },
    {
      colorName: 'color-indigo-400',
      bgClass: 'bg-indigo-400',
      iconClass: 'after:bg-indigo-800!',
      textClass: 'text-indigo-800',
      softClass: 'text-indigo-400',
    },
    {
      colorName: 'color-indigo-500',
      bgClass: 'bg-indigo-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-indigo-500',
    },
    {
      colorName: 'color-indigo-600',
      bgClass: 'bg-indigo-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-indigo-600',
    },
    {
      colorName: 'color-indigo-700',
      bgClass: 'bg-indigo-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-indigo-700',
    },
    {
      colorName: 'color-indigo-800',
      bgClass: 'bg-indigo-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-indigo-800',
    },
    {
      colorName: 'color-indigo-900',
      bgClass: 'bg-indigo-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-indigo-900',
    },
    {
      colorName: 'color-indigo-950',
      bgClass: 'bg-indigo-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-indigo-950',
    },
  ],
  // VIOLET
  [
    {
      colorName: 'color-violet-50',
      bgClass: 'bg-violet-50',
      iconClass: 'after:bg-violet-500!',
      textClass: 'text-violet-500',
      softClass: 'text-violet-50',
    },
    {
      colorName: 'color-violet-100',
      bgClass: 'bg-violet-100',
      iconClass: 'after:bg-violet-500!',
      textClass: 'text-violet-500',
      softClass: 'text-violet-100',
    },
    {
      colorName: 'color-violet-200',
      bgClass: 'bg-violet-200',
      iconClass: 'after:bg-violet-500!',
      textClass: 'text-violet-500',
      softClass: 'text-violet-200',
    },
    {
      colorName: 'color-violet-300',
      bgClass: 'bg-violet-300',
      iconClass: 'after:bg-violet-700!',
      textClass: 'text-violet-700',
      softClass: 'text-violet-300',
    },
    {
      colorName: 'color-violet-400',
      bgClass: 'bg-violet-400',
      iconClass: 'after:bg-violet-800!',
      textClass: 'text-violet-800',
      softClass: 'text-violet-400',
    },
    {
      colorName: 'color-violet-500',
      bgClass: 'bg-violet-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-violet-500',
    },
    {
      colorName: 'color-violet-600',
      bgClass: 'bg-violet-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-violet-600',
    },
    {
      colorName: 'color-violet-700',
      bgClass: 'bg-violet-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-violet-700',
    },
    {
      colorName: 'color-violet-800',
      bgClass: 'bg-violet-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-violet-800',
    },
    {
      colorName: 'color-violet-900',
      bgClass: 'bg-violet-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-violet-900',
    },
    {
      colorName: 'color-violet-950',
      bgClass: 'bg-violet-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-violet-950',
    },
  ],
  // PURPLE
  [
    {
      colorName: 'color-purple-50',
      bgClass: 'bg-purple-50',
      iconClass: 'after:bg-purple-500!',
      textClass: 'text-purple-500',
      softClass: 'text-purple-50',
    },
    {
      colorName: 'color-purple-100',
      bgClass: 'bg-purple-100',
      iconClass: 'after:bg-purple-500!',
      textClass: 'text-purple-500',
      softClass: 'text-purple-100',
    },
    {
      colorName: 'color-purple-200',
      bgClass: 'bg-purple-200',
      iconClass: 'after:bg-purple-500!',
      textClass: 'text-purple-500',
      softClass: 'text-purple-200',
    },
    {
      colorName: 'color-purple-300',
      bgClass: 'bg-purple-300',
      iconClass: 'after:bg-purple-700!',
      textClass: 'text-purple-700',
      softClass: 'text-purple-300',
    },
    {
      colorName: 'color-purple-400',
      bgClass: 'bg-purple-400',
      iconClass: 'after:bg-purple-800!',
      textClass: 'text-purple-800',
      softClass: 'text-purple-400',
    },
    {
      colorName: 'color-purple-500',
      bgClass: 'bg-purple-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-purple-500',
    },
    {
      colorName: 'color-purple-600',
      bgClass: 'bg-purple-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-purple-600',
    },
    {
      colorName: 'color-purple-700',
      bgClass: 'bg-purple-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-purple-700',
    },
    {
      colorName: 'color-purple-800',
      bgClass: 'bg-purple-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-purple-800',
    },
    {
      colorName: 'color-purple-900',
      bgClass: 'bg-purple-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-purple-900',
    },
    {
      colorName: 'color-purple-950',
      bgClass: 'bg-purple-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-purple-950',
    },
  ],
  // FUCHSIA
  [
    {
      colorName: 'color-fuchsia-50',
      bgClass: 'bg-fuchsia-50',
      iconClass: 'after:bg-fuchsia-500!',
      textClass: 'text-fuchsia-500',
      softClass: 'text-fuchsia-50',
    },
    {
      colorName: 'color-fuchsia-100',
      bgClass: 'bg-fuchsia-100',
      iconClass: 'after:bg-fuchsia-500!',
      textClass: 'text-fuchsia-500',
      softClass: 'text-fuchsia-100',
    },
    {
      colorName: 'color-fuchsia-200',
      bgClass: 'bg-fuchsia-200',
      iconClass: 'after:bg-fuchsia-500!',
      textClass: 'text-fuchsia-500',
      softClass: 'text-fuchsia-200',
    },
    {
      colorName: 'color-fuchsia-300',
      bgClass: 'bg-fuchsia-300',
      iconClass: 'after:bg-fuchsia-700!',
      textClass: 'text-fuchsia-700',
      softClass: 'text-fuchsia-300',
    },
    {
      colorName: 'color-fuchsia-400',
      bgClass: 'bg-fuchsia-400',
      iconClass: 'after:bg-fuchsia-800!',
      textClass: 'text-fuchsia-800',
      softClass: 'text-fuchsia-400',
    },
    {
      colorName: 'color-fuchsia-500',
      bgClass: 'bg-fuchsia-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-fuchsia-500',
    },
    {
      colorName: 'color-fuchsia-600',
      bgClass: 'bg-fuchsia-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-fuchsia-600',
    },
    {
      colorName: 'color-fuchsia-700',
      bgClass: 'bg-fuchsia-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-fuchsia-700',
    },
    {
      colorName: 'color-fuchsia-800',
      bgClass: 'bg-fuchsia-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-fuchsia-800',
    },
    {
      colorName: 'color-fuchsia-900',
      bgClass: 'bg-fuchsia-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-fuchsia-900',
    },
    {
      colorName: 'color-fuchsia-950',
      bgClass: 'bg-fuchsia-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-fuchsia-950',
    },
  ],
  // PINK
  [
    {
      colorName: 'color-pink-50',
      bgClass: 'bg-pink-50',
      iconClass: 'after:bg-pink-500!',
      textClass: 'text-pink-500',
      softClass: 'text-pink-50',
    },
    {
      colorName: 'color-pink-100',
      bgClass: 'bg-pink-100',
      iconClass: 'after:bg-pink-500!',
      textClass: 'text-pink-500',
      softClass: 'text-pink-100',
    },
    {
      colorName: 'color-pink-200',
      bgClass: 'bg-pink-200',
      iconClass: 'after:bg-pink-500!',
      textClass: 'text-pink-500',
      softClass: 'text-pink-200',
    },
    {
      colorName: 'color-pink-300',
      bgClass: 'bg-pink-300',
      iconClass: 'after:bg-pink-700!',
      textClass: 'text-pink-700',
      softClass: 'text-pink-300',
    },
    {
      colorName: 'color-pink-400',
      bgClass: 'bg-pink-400',
      iconClass: 'after:bg-pink-800!',
      textClass: 'text-pink-800',
      softClass: 'text-pink-400',
    },
    {
      colorName: 'color-pink-500',
      bgClass: 'bg-pink-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-pink-500',
    },
    {
      colorName: 'color-pink-600',
      bgClass: 'bg-pink-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-pink-600',
    },
    {
      colorName: 'color-pink-700',
      bgClass: 'bg-pink-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-pink-700',
    },
    {
      colorName: 'color-pink-800',
      bgClass: 'bg-pink-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-pink-800',
    },
    {
      colorName: 'color-pink-900',
      bgClass: 'bg-pink-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-pink-900',
    },
    {
      colorName: 'color-pink-950',
      bgClass: 'bg-pink-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-pink-950',
    },
  ],
  // ROSE
  [
    {
      colorName: 'color-rose-50',
      bgClass: 'bg-rose-50',
      iconClass: 'after:bg-rose-500!',
      textClass: 'text-rose-500',
      softClass: 'text-rose-50',
    },
    {
      colorName: 'color-rose-100',
      bgClass: 'bg-rose-100',
      iconClass: 'after:bg-rose-500!',
      textClass: 'text-rose-500',
      softClass: 'text-rose-100',
    },
    {
      colorName: 'color-rose-200',
      bgClass: 'bg-rose-200',
      iconClass: 'after:bg-rose-500!',
      textClass: 'text-rose-500',
      softClass: 'text-rose-200',
    },
    {
      colorName: 'color-rose-300',
      bgClass: 'bg-rose-300',
      iconClass: 'after:bg-rose-700!',
      textClass: 'text-rose-700',
      softClass: 'text-rose-300',
    },
    {
      colorName: 'color-rose-400',
      bgClass: 'bg-rose-400',
      iconClass: 'after:bg-rose-800!',
      textClass: 'text-rose-800',
      softClass: 'text-rose-400',
    },
    {
      colorName: 'color-rose-500',
      bgClass: 'bg-rose-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-rose-500',
    },
    {
      colorName: 'color-rose-600',
      bgClass: 'bg-rose-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-rose-600',
    },
    {
      colorName: 'color-rose-700',
      bgClass: 'bg-rose-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-rose-700',
    },
    {
      colorName: 'color-rose-800',
      bgClass: 'bg-rose-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-rose-800',
    },
    {
      colorName: 'color-rose-900',
      bgClass: 'bg-rose-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-rose-900',
    },
    {
      colorName: 'color-rose-950',
      bgClass: 'bg-rose-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-rose-950',
    },
  ],
  // SLATE
  [
    {
      colorName: 'color-slate-50',
      bgClass: 'bg-slate-50',
      iconClass: 'after:bg-slate-500!',
      textClass: 'text-slate-500',
      softClass: 'text-slate-50',
    },
    {
      colorName: 'color-slate-100',
      bgClass: 'bg-slate-100',
      iconClass: 'after:bg-slate-500!',
      textClass: 'text-slate-500',
      softClass: 'text-slate-100',
    },
    {
      colorName: 'color-slate-200',
      bgClass: 'bg-slate-200',
      iconClass: 'after:bg-slate-500!',
      textClass: 'text-slate-500',
      softClass: 'text-slate-200',
    },
    {
      colorName: 'color-slate-300',
      bgClass: 'bg-slate-300',
      iconClass: 'after:bg-slate-700!',
      textClass: 'text-slate-700',
      softClass: 'text-slate-300',
    },
    {
      colorName: 'color-slate-400',
      bgClass: 'bg-slate-400',
      iconClass: 'after:bg-slate-800!',
      textClass: 'text-slate-800',
      softClass: 'text-slate-400',
    },
    {
      colorName: 'color-slate-500',
      bgClass: 'bg-slate-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-slate-500',
    },
    {
      colorName: 'color-slate-600',
      bgClass: 'bg-slate-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-slate-600',
    },
    {
      colorName: 'color-slate-700',
      bgClass: 'bg-slate-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-slate-700',
    },
    {
      colorName: 'color-slate-800',
      bgClass: 'bg-slate-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-slate-800',
    },
    {
      colorName: 'color-slate-900',
      bgClass: 'bg-slate-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-slate-900',
    },
    {
      colorName: 'color-slate-950',
      bgClass: 'bg-slate-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-slate-950',
    },
  ],
  // GRAY
  [
    {
      colorName: 'color-gray-50',
      bgClass: 'bg-gray-50',
      iconClass: 'after:bg-gray-500!',
      textClass: 'text-gray-500',
      softClass: 'text-gray-50',
    },
    {
      colorName: 'color-gray-100',
      bgClass: 'bg-gray-100',
      iconClass: 'after:bg-gray-500!',
      textClass: 'text-gray-500',
      softClass: 'text-gray-100',
    },
    {
      colorName: 'color-gray-200',
      bgClass: 'bg-gray-200',
      iconClass: 'after:bg-gray-500!',
      textClass: 'text-gray-500',
      softClass: 'text-gray-200',
    },
    {
      colorName: 'color-gray-300',
      bgClass: 'bg-gray-300',
      iconClass: 'after:bg-gray-700!',
      textClass: 'text-gray-700',
      softClass: 'text-gray-300',
    },
    {
      colorName: 'color-gray-400',
      bgClass: 'bg-gray-400',
      iconClass: 'after:bg-gray-800!',
      textClass: 'text-gray-800',
      softClass: 'text-gray-400',
    },
    {
      colorName: 'color-gray-500',
      bgClass: 'bg-gray-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-gray-500',
    },
    {
      colorName: 'color-gray-600',
      bgClass: 'bg-gray-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-gray-600',
    },
    {
      colorName: 'color-gray-700',
      bgClass: 'bg-gray-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-gray-700',
    },
    {
      colorName: 'color-gray-800',
      bgClass: 'bg-gray-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-gray-800',
    },
    {
      colorName: 'color-gray-900',
      bgClass: 'bg-gray-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-gray-900',
    },
    {
      colorName: 'color-gray-950',
      bgClass: 'bg-gray-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-gray-950',
    },
  ],
  // ZINC
  [
    {
      colorName: 'color-zinc-50',
      bgClass: 'bg-zinc-50',
      iconClass: 'after:bg-zinc-500!',
      textClass: 'text-zinc-500',
      softClass: 'text-zinc-50',
    },
    {
      colorName: 'color-zinc-100',
      bgClass: 'bg-zinc-100',
      iconClass: 'after:bg-zinc-500!',
      textClass: 'text-zinc-500',
      softClass: 'text-zinc-100',
    },
    {
      colorName: 'color-zinc-200',
      bgClass: 'bg-zinc-200',
      iconClass: 'after:bg-zinc-500!',
      textClass: 'text-zinc-500',
      softClass: 'text-zinc-200',
    },
    {
      colorName: 'color-zinc-300',
      bgClass: 'bg-zinc-300',
      iconClass: 'after:bg-zinc-700!',
      textClass: 'text-zinc-700',
      softClass: 'text-zinc-300',
    },
    {
      colorName: 'color-zinc-400',
      bgClass: 'bg-zinc-400',
      iconClass: 'after:bg-zinc-800!',
      textClass: 'text-zinc-800',
      softClass: 'text-zinc-400',
    },
    {
      colorName: 'color-zinc-500',
      bgClass: 'bg-zinc-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-zinc-500',
    },
    {
      colorName: 'color-zinc-600',
      bgClass: 'bg-zinc-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-zinc-600',
    },
    {
      colorName: 'color-zinc-700',
      bgClass: 'bg-zinc-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-zinc-700',
    },
    {
      colorName: 'color-zinc-800',
      bgClass: 'bg-zinc-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-zinc-800',
    },
    {
      colorName: 'color-zinc-900',
      bgClass: 'bg-zinc-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-zinc-900',
    },
    {
      colorName: 'color-zinc-950',
      bgClass: 'bg-zinc-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-zinc-950',
    },
  ],
  // NEUTRAL
  [
    {
      colorName: 'color-neutral-50',
      bgClass: 'bg-neutral-50',
      iconClass: 'after:bg-neutral-500!',
      textClass: 'text-neutral-500',
      softClass: 'text-neutral-50',
    },
    {
      colorName: 'color-neutral-100',
      bgClass: 'bg-neutral-100',
      iconClass: 'after:bg-neutral-500!',
      textClass: 'text-neutral-500',
      softClass: 'text-neutral-100',
    },
    {
      colorName: 'color-neutral-200',
      bgClass: 'bg-neutral-200',
      iconClass: 'after:bg-neutral-500!',
      textClass: 'text-neutral-500',
      softClass: 'text-neutral-200',
    },
    {
      colorName: 'color-neutral-300',
      bgClass: 'bg-neutral-300',
      iconClass: 'after:bg-neutral-700!',
      textClass: 'text-neutral-700',
      softClass: 'text-neutral-300',
    },
    {
      colorName: 'color-neutral-400',
      bgClass: 'bg-neutral-400',
      iconClass: 'after:bg-neutral-800!',
      textClass: 'text-neutral-800',
      softClass: 'text-neutral-400',
    },
    {
      colorName: 'color-neutral-500',
      bgClass: 'bg-neutral-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-neutral-500',
    },
    {
      colorName: 'color-neutral-600',
      bgClass: 'bg-neutral-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-neutral-600',
    },
    {
      colorName: 'color-neutral-700',
      bgClass: 'bg-neutral-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-neutral-700',
    },
    {
      colorName: 'color-neutral-800',
      bgClass: 'bg-neutral-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-neutral-800',
    },
    {
      colorName: 'color-neutral-900',
      bgClass: 'bg-neutral-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-neutral-900',
    },
    {
      colorName: 'color-neutral-950',
      bgClass: 'bg-neutral-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-neutral-950',
    },
  ],
  // STONE
  [
    {
      colorName: 'color-stone-50',
      bgClass: 'bg-stone-50',
      iconClass: 'after:bg-stone-500!',
      textClass: 'text-stone-500',
      softClass: 'text-stone-50',
    },
    {
      colorName: 'color-stone-100',
      bgClass: 'bg-stone-100',
      iconClass: 'after:bg-stone-500!',
      textClass: 'text-stone-500',
      softClass: 'text-stone-100',
    },
    {
      colorName: 'color-stone-200',
      bgClass: 'bg-stone-200',
      iconClass: 'after:bg-stone-500!',
      textClass: 'text-stone-500',
      softClass: 'text-stone-200',
    },
    {
      colorName: 'color-stone-300',
      bgClass: 'bg-stone-300',
      iconClass: 'after:bg-stone-700!',
      textClass: 'text-stone-700',
      softClass: 'text-stone-300',
    },
    {
      colorName: 'color-stone-400',
      bgClass: 'bg-stone-400',
      iconClass: 'after:bg-stone-800!',
      textClass: 'text-stone-800',
      softClass: 'text-stone-400',
    },
    {
      colorName: 'color-stone-500',
      bgClass: 'bg-stone-500',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-stone-500',
    },
    {
      colorName: 'color-stone-600',
      bgClass: 'bg-stone-600',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-stone-600',
    },
    {
      colorName: 'color-stone-700',
      bgClass: 'bg-stone-700',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-stone-700',
    },
    {
      colorName: 'color-stone-800',
      bgClass: 'bg-stone-800',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-stone-800',
    },
    {
      colorName: 'color-stone-900',
      bgClass: 'bg-stone-900',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-stone-900',
    },
    {
      colorName: 'color-stone-950',
      bgClass: 'bg-stone-950',
      iconClass: 'after:bg-white!',
      textClass: 'text-white',
      softClass: 'text-stone-950',
    },
  ],
];

export function getColorByName(colorName: string): Color | null {
  for (const colorGroup of COLORS) {
    for (const color of colorGroup) {
      if (color.colorName === colorName) {
        return color;
      }
    }
  }
  return null;
}

export function colorNameToFontClass(colorName: string): string {
  return colorName.replace(/^color-/, 'text-');
}
